[package]
name = "todo_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }
serde = "1.0.136"
dotenv = "0.15.0"
mongodb = "2.0"
serde_json = "1.0"
chrono = "0.4.38"
futures = "0.3.30"
